name: CSV Karcsusito Automatizmus

on:
  schedule:
    - cron: '0 3 * * *'  # Minden nap 03:00 UTC
  workflow_dispatch:      # Manuális indítás lehetősége

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repó kiírása
        uses: actions/checkout@v4

      - name: Python környezet beállítása
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Script futtatása
        run: python script.py

      - name: Letölthető Release frissítése
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Legfrissebb Karcsúsított CSV
          files: karcsusitott_feed.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
